### ISSUE TITLE
Allow access to current indentation level

### ISSUE THREAD

**Issue by mullermp** [awslabs/smithy#1017]
It would be useful to retrieve the current indentation level, so a character limit can be calculated for string wrapping. I.e. if indented 4 levels, with 2 spaces each, and targeting 120 characters max line length, we would wrap on 112 characters.

Going even further, it would be great to see `StringUtils.wrap` better integrated with CodeWriter writing. Perhaps instead of exposing indentation level, CodeWriter could supply a writeWrap method that wrote text and automatically wrapped it to a set maximum length.

**Comment by mtdowling** [comment]
The current indentation level would probably not be useful because the number of characters used for indentation can change per/state. Giving the current indentation string might be useful though tricky since things like filters can alter the contents of a block, and they can adjust the indentation. Getting the current column on the current line would be interesting, but also hard because of filters. Maybe the best we could do is an estimate since we can't account for filters.

For example, a filter like this could prefix each line with two characters while still allowing for custom indentation:

```java
CodeWriter writer = new CodeWriter();
writer.pushFilteredState(s -> "# " + s.replace("\n", "\n# "));
writer.write("hello");
writer.popState();
```

A filter might be a nice way to implement word wrapping. It would likely need to be configurable as to how things are wrapped... maybe that could be done using two states:

```java
CodeWriter writer = new CodeWriter();
writer.pushFilteredState(s -> "# " + s.replace("\n", "\n# "));
writer.pushFilteredState(text -> StringUtils.wrap(text, 78));
writer.write("@!attribute some_member this is more test this should wrap right??? It should I think it will.");
writer.indent();
writer.write("this is a");
writer.write("comment");
writer.dedent();
writer.write("Goodbye!");
writer.popState();
writer.popState();
```

The issue above is you need to know the current column in order to know the max length.

**Comment by mullermp** [comment]
I don't think that example works for me - the output is:
```
# @!attribute some_member this is more test this should wrap right??? It should
# I think it will.
#   this is a
#   comment
# Goodbye!
```
With wrapping, it should be indented in the next line:

```
# @!attribute some_member this is more test this should wrap right??? It should
#   I think it will.           <-- this wrapping should be indented, otherwise it's not part of @!attribute tag
#     this is a                  <-- I suppose this should be "indented" again because of indent() call?
#     comment
#   Goodbye!
```

**Comment by mtdowling** [comment]
CodeWriter now provides getIndentText and getIndentLevel.
