### ISSUE TITLE
Silent execution/warnings as errors

### ISSUE THREAD

**Issue by lunaris** [awslabs/smithy#1062]
Currently, it's not (I don't believe) possible to run `smithy build` in a manner that is truly quiet/silent -- one always receives some output. There is the `--logging` flag, which has an `OFF` value, but this does not apply to the output of the `Validator`, which always outputs statistics about how the model fared against various validations, etc.

A use case we have for truly silent execution is calling Smithy as part of a larger build process (e.g. Bazel). Here Smithy's output generates noise we'd rather not see. Of course, this only pertains to the "happy path", so the ideal would be to hook in the Validator's output to correspond to the logging level -- if the level is warning, Smithy outputs warnings; if the level if error, Smithy outputs errors and so on. Coupled with this it would be useful if Smithy had a flag like `-Werror` for promoting warnings to errors.

There are a few ways I can see about implementing this in the Smithy codebase (with https://github.com/awslabs/smithy/blob/7ea2682a5ab3c5cd6794c826c33121fa6dd40bf2/smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildCommand.java#L109 being a starting point), but wanted to raise an issue first to see a. if this is of interest/the use case is a valid one that makes sense and b. whether or not there are other considerations to be made that I have missed. Thanks in advance for your thoughts!

**Comment by mtdowling** [comment]
Yeah,`-- logging` right now doesn't impact other informational output.

Both the `build` and `validate` commands have a `--severity` parameter which I think is a clearer way to control Smithy validation output (that is, showing the issues that were detected while validating the model, not the logging output). The default logging level I think is INFO, and that's controlled with `--logging`.

We have a `--debug` option which turns everything up all the way (--logging, --severity, etc). Or at least it should if it doesn't already.

Since we have a `--debug` flag, maybe we should add a mutually exclusive `--silent` flag? We'd check if the silent flag is set before writing to stdout/stderr for informational stuff. It could automatically set a default value of `--logging` to `OFF`, and `--severity` to `DANGER` so that you'd see when anything fails the build. Both `--logging` and `--severity` could be explicitly configured when using `--silent` too; for example, you could use `--silent` to turn off informational output, but set `--loging` to SEVERE to see more error information.

Would that work?

As for promoting warnings to errors, we have a feature request for that, but need to figure out a good place for it:  https://github.com/awslabs/smithy/issues/856

**Comment by lunaris** [comment]
Thanks for the response!

On first blush it feels like `--silent` setting `--severity` to `DANGER` is outside its remit, but I don't have super strong feelings on that front. Would you take a PR to try and introduce `--silent` to the codebase in this vein? And regarding the validation messages referenced in my original message, is the idea that they should be suppressed by virtue of setting `severity`, rather than porting them to use the existing logging tools? Because looking at the code that's not currently the case and would have to be handled as part of these changes, no?

**Comment by lunaris** [comment]
Would be great to get a steer on whether or not a contribution like this would be accepted/in alignment with how we want the tools to work -- if so I'd be happy to take a stab at it as we'd really benefit from this.

**Comment by mtdowling** [comment]
Yes! A PR would be welcome!

**Comment by mtdowling** [comment]
I added a `--quiet` flag to all commands: https://github.com/awslabs/smithy/pull/1257
