### ISSUE TITLE
Allow operation output to be union of structures

### ISSUE THREAD

**Issue by eduardomourar** [awslabs/smithy#1112]
If we try to create an operation output that is a union of multiple structures, like below:

```
structure CompletedResponse {}

structure InProgressResponse {}

union ExampleOutput {
  completed: CompletedResponse,
  inProgress: InProgressResponse,
}
```

We get the following error:

> operation shape `output` relationships must target a structure shape, but found (union: `com.example#ExampleOutput`)

I expected the validation step to check for `structure` shapes, but that it would allow `unions` as long as included only `structure` in it.

**Comment by JordonPhillips** [comment]
The types that a union points to aren't particularly important. There is no special handling of a union that returns only booleans or only lists as member values for example.

A union is unsuitable to use as an operation input / output because it isn't capable of evolving in the way that inputs / outputs often need to. Day 1 that union might be fine, there may be no duplicated information across your target shapes and maybe they're even all the same shape type. But on Day 2 you find you need to unconditionally add some metadata to every response. So now you have to ensure that you add this to every union target, and make sure you always set it in every pathway in your code. Then every time you or some other engineer adds a new member in the future, you need to make sure you add those in and that the member target is even capable of holding them. That's a lot of risk.

In this case what you would do is just make your union a member of the input / output structure. You could, for example, call it `Status`. This is not entirely dissimilar to what lambda does, where they bind the http status code and return a 201 if the operation is still in progress. The major difference being that a union with legible details is probably a better experience. But this does allow you to continue to evolve your service safely.

**Comment by eduardomourar** [comment]
It makes sense. In our case, we have a very limited set of possibilities similar to the [Cloud Control ProgressEvent type](https://docs.aws.amazon.com/cloudcontrolapi/latest/APIReference/API_ProgressEvent.html). We want to define a single response to an asynchronous API where you have 3 outputs: `FailedResponse`, `InProgressReponse` and `SucessResponse`. The way you saying we have to do is wrap around a property such as `status`. We would love to just flatten it by defining a union directly so that we will evolve the shape but based on each individual category response instead.

**Comment by mtdowling** [comment]
Jordon gave good examples of how this isn't a good idea for Smithy in general, but also this simply is impossible at this point without breaking thousands of models and every existing Smithy implementation. It's a huge simplification in the meta model that every input is a structure and every output is a structure.

If you want to modify the serialization of an HTTP request or response to use a union as the payload of the message, you can do so by appyling an `@httpPayload` trait to a member of your input/output structure that targets a union (assuming your're using an HTTP protocol).
