### ISSUE TITLE
Some sort of trait abstraction capabilities?

### ISSUE THREAD

**Issue by copumpkin** [awslabs/smithy#116]
I'm finding myself writing nearly the same `@paginated` all over my smithy code because I want the same token/maxresults variables and consistency across my API. The only thing that meaningfully varies is the `items` field.

I was wondering if it was currently (or could become) possible to have some sort of `@copumpkinPaginated(items: Foo)` where I define `@copumpkinPaginated` in one place and then reuse it everywhere else, and it expands to `@paginated` with the right arguments.

More generally it seems like some sort of basic macro system would be nice. I've considered layering even the C preprocessor over smithy to avoid writing all the `XRequest` `XResponse` structures out by hand.

**Comment by mtdowling** [comment]
We actually added this very pagination feature a few days ago :) You can attach the `@paginated` trait to a service shape, which will provide default values to every operation that is marked as `@paginated` in the closure of a service. For example:

```
namespace smithy.example

@paginated(inputToken: "nextToken", outputToken: "nextToken",
           pageSize: "maxResults")
service Example {
  version: "2019-06-27",
  operations: [GetFoos],
}

@collection @readonly @paginated(items: "foos")
operation GetFoos(GetFoosInput) -> GetFoosOutput
```

We've been kicking around the idea of macros or some kind of trait inheritance feature, and we're very open to ideas and proposals around this. We continue to shy away from it due to the complexity it adds to just about everything related to loading the model, and we think it could sacrifice readability of the model due to the indirection.

**Comment by copumpkin** [comment]
Nice! Agree that macros are a bit of a potential mess, and am not sure how I'd implement them in smithy other.

**Comment by mtdowling** [comment]
We recently shipped an update that makes traits a specialization of shapes. If you attach `@trait` to a shape it becomes a trait. This means that traits can be attached to trait definitions, opening up some interesting future possibilities in this space.

**Comment by mtdowling** [comment]
I'll go ahead and close this since we addressed the paginated issue, we both agree that macros seem like they have too steep a tradeoff, and we added the ability to add traits to traits. I think we'll be able to use this feature to figure out other extension points for traits in the future.
