### ISSUE TITLE
HttpHeaderTraitValidator is overly constraining

### ISSUE THREAD

**Issue by Baccata** [awslabs/smithy#1160]
<img width="904" alt="Screenshot 2022-03-27 at 17 08 08" src="https://user-images.githubusercontent.com/4439335/160287998-047ae07d-92f4-453a-ab12-41a1130a58d1.png">

Though this might be a pragmatic constraint in the context of AWS services (in particular with regards to SDKs), concepts like authorisation might be valid domain-specific concerns in many usecases, and making it harder to define specs that need these headers is counter productive. This is especially problematic on the server side. 

It is possible to suppress this validation, but most users do not know how to do it and editor support doesn't currently help. Thus, users get blocked pretty easily on this. In the tooling I personally write, this problem can be solved via middleware, but it makes the UX a little bit awkward to less experienced developers. 

I'd like to propose two simple changes : 

1. the decoupling/split of the current [HttpHeaderTraitValidator](https://github.com/awslabs/smithy/blob/main/smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpHeaderTraitValidator.java) class into two distinct validators, thus making it easier to suppress the header blocklist without making it seem like we're suppressing more fundamental rules relative to httpHeaders 
2. the relaxing of the severity from Danger to Warning for the verification of headers related to the blocklist

**Comment by mtdowling** [comment]
Why not use one of the existing authentication scheme traits? Auth traits are designed to manage auth at the framework level. Putting these into an API directly requires callers to provide auth for each invocation of the operation rather than through framework abstractions that automatically provide authentication headers.

Making these user-configurable is problematic for interop with other specs too, like OpenAPI:

>If [in](https://swagger.io/specification/#parameter-in) is "header" and the name field is "Accept", "Content-Type" or "Authorization", the parameter definition SHALL be ignored.

Moving the blocklist validation to another validator would cause existing `HttpHeaderTrait` suppressions to no longer apply, so that sounds tricky to do without impacting existing models. I'm also hesitant to lessen the severity here because these headers are more framework headers rather than user-provided headers (most of these headers are either nonsensical to provide or dangerous). We've seen that people often ignore warnings, so DANGER is used to force modelers to acknowledge the risk and see if there's a better way to model something.

> It is possible to suppress this validation, but most users do not know how to do it 

Maybe the warning could add a note that it can be suppressed?

**Comment by Baccata** [comment]
> Why not use one of the existing authentication scheme traits? Auth traits are designed to manage auth at the framework level. 

I'll try to rephrase : my point is that auth is not always a framework concern, it is sometimes a domain one. 

Say you're implementing a service (therefore, server-side) and need to perform a database call to retrieve information related to the user associated to the auth token you received. This implies that you need to access the value of the auth token during the implementation of the generated methods that come from the service. Having the value available as a method parameter is convenient to the developer. 

> Putting these into an API directly requires callers to provide auth for each invocation of the operation rather than through framework abstractions that automatically provide authentication headers.

That is not necessarily the case, thanks to `smithy-build` (the idea behind it is excellent btw) : the model used by client-side tooling doesn't have to b e the same as the model used by server-side tooling, so what is domain-level concern on one side may very much be framework-level concern on the other, and the client-side framework would be responsible for auto-filling the header. 

That being said, I can see now that a very easy rebuttal point would be "yeah but why not doing the pre-processing so that the auth header membe is hidden in the "source of truth spec", and that'd be a very valid point. 

> Moving the blocklist validation to another validator would cause existing HttpHeaderTrait suppressions to no longer apply, so that sounds tricky to do without impacting existing models 

This would be less problematic if combined the severity of the error was relaxed to warning. 

> Maybe the warning could add a note that it can be suppressed? 

I suppose that'd help. I think the IDE could be better in that regard, adding the name of the validator in the diagnostic would definitely help knowing what to suppress, and that'd be an easy addition.

**Comment by adamthom-amzn** [comment]
We have traditionally not allowed direct userland access to these headers in our frameworks because they are often at the wrong level of abstraction for service developers. We have seen issues with service developers assuming some values from headers are authoritative when in practice they are not (for instance, if the service supports two different authentication methods, but does not reject requests that contain additional information that would traditionally be associated with a different authentication method).

What we have traditionally done has been to introduce a higher-level abstraction representing authoritative information about the caller that is populated by the auth middleware. This means that application developers have a source of data they can trust without being coupled to the particular mechanisms by which that data is acquired - or needing expertise in how to acquire that data in a trusted manner.

**Comment by Baccata** [comment]
Hey Adam, sorry to reply only now

> We have traditionally not allowed direct userland access to these headers in our frameworks because they are often at the wrong level of abstraction for service developers 

With respect to the grand majority of usecases, I agree with you. The problem that I have with your sentence is : "in **our** frameworks". My organisation is quite invested in smithy now, and that is because of its inherent qualities as a metamodel/syntax/core-tooling (I'm talking about the library in this very repo), not because of the code generators and associated mechanisms AWS may provide in the future. smithy is an excellent IDL, and allows for usecases that go way past what AWS has designed it for. And that is, in my humble opinion, a **very good thing**. As a result, we are building our own tooling 

In the context of this issue: the motivation is primarily the fact that the `http` traits are general enough to be re-used across multiple protocols. For instance, we at DisneyStreaming are using them in our own `disneyRestJson` protocol that captures semantics that the `awsRestJson` protocol does not. These are semantics that have been used implicitly in some of our existing services that we want to retro-fit a smithy specification for. So we're already using the `http` traits in a usecase that is not encompassed by the design of the AWS tooling. 

Now I do believe that it's fair to have this kind of validation built-in the default validators, but I also think it's important for AWS to recognise the fact that smithy will/is used outside of the usecases you guys have thought about, and outside of your tooling, and that these usecases virtually illegitimate by means of validators that could be described as AWS-centric (and should, imho, be tied to the presence of aws-specific protocols) creates a little friction. 

`<devils_advocate>`

I could also go as far as saying that the existence of the [httpResponseCode](https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html?highlight=http%20bindings#httpresponsecode-trait) trait creates a double-standard, as it arguably fits in the same category of "wrong level of abstraction" that you describe. 

`</devils_advocate>`

Anyway, these are my two cents. I'm not too fussed. After all, the validation can be suppressed, and therefore this issue does not constitute a hard blocker.

**Comment by adamthom-amzn** [comment]
I agree with you about `httpResponseCode`, and in fact I'd go even further and say most of what an HTTP binding protocol does is surface the wire format in the model and force the modeler to think at the wrong level of abstraction.

**Comment by Baccata** [comment]
Not sure I fully agree with you there, as the design seems to happen in different stages, first being what data is, second being where the data goes. There's a lot less bikeshedding with smithy than there is with, say, openapi. 

The httpResponseCode is particular in that if you use it, you've necessarily polluted your domain model with protocol level constraints. The underlying integer cannot have any meaning but something that is totally specific to http protocols.

In our platform, we have some domain level data that can sometimes be embedded in headers, and there's a perfectly acceptable rationale for it. But I cannot see a good reason why httpResponseCode would ever be used. 

That's okay though, because I'm happy with acknowledging that other people may have a totally acceptable rationale for its use.

**Comment by jakepearson** [comment]
Hi, I'm facing a similar challenge with not being able to map the `Authorization` header to a field in my model. I would like to make an additional call to another API using the original requestor's `Authorization` header in my lambda code. It seems like the straightforward way to accomplish this is with a field like:

``` smithy 
@header("Authorization")
authorization: String
```

Is there another way to accomplish this?

**Comment by mtdowling** [comment]
This validation can be suppressed (e.g., `@suppress(["HttpHeaderTrait"])`).

But really, this use case sounds like something that should be handled using middleware/extensions that inject HTTP headers after a request is serialized. By explicitly setting things like Authorization headers and not using the abstractions provided by Smithy like the auth traits, then you're breaking through a layer of abstraction. That's where things like middleware and modifying HTTP requests at runtime in the client come in.

I'm going to close this since we don't plan on removing this validation.

**Comment by pedrettin** [comment]
I have a similar usecase but for the `www-authorize` header.  My server follows the RFC oath2 protocol and needs to return a `www-authorize` header on `AuthenticationError`. This is how I intended to do it

```
@error("client")
@httpError(401)
structure AuthorizationError {
    @required
    @default("Request not authorized")
    message: String,
    @httpHeader("www-authenticate")
    auth_header: AuthHeader,
}
```

This way when i build the error in my server I can attach all the header information to let the client know how/where to fetch the authorization token. If this way is not correct, what would be the correct way of handling this case?

**Comment by kstich** [comment]
That is the correct path, you'll also need to apply a suppression for that validation event (e.g., `@suppress(["HttpHeaderTrait"])`).
