### ISSUE TITLE
Allow inline lists

### ISSUE THREAD

**Issue by kubukoz** [awslabs/smithy#1223]
Hi! I saw https://github.com/awslabs/smithy/blob/idl-2.0-rc-1/designs/inline-io.md and wondered if something similar could happen for lists:

instead of

```
structure User {
  names: Names
}

list Names { member: Name }
```

it would be possible to do

```
structure User {
  names: [Name]
}
```

(or similar) and a shape like `Names` could be implicitly assumed to exist without the spec author having to write it.

This is not only a syntactic convenience, it would also aid refactoring (fewer symbols to rename).

Thanks :)

**Comment by mtdowling** [comment]
For inline operation input/output, we saw that teams were almost always creating dedicated input and output shapes in their models, naming them consistently (e.g., `PutFooInput`, `PutFooOutput`), and rarely ever applying traits to them. Despite synthesizing these shapes, the end result is that the name is still deterministic so you could do stuff like add traits to the synthesized I/O shapes.

We thought inline lists as less of a slam dunk (and sets and maps), but I'm curious about your thoughts on this.

Teams often need to apply traits to lists (like `@length`, `@documentation`, `@sparse`) and traits to the member of the list (docs, other constraints). If we accounted for this in syntax, then sure it could work, but it won't look as nice and succinct. Like:

```
// This could support adding a trait to the member, but oof!
// We'd probably just not support member traits with an inline syntax.
structure User {
    names := @sparse Name[@length(min: 1)]
}
```

We think this would reduce the amount of shape sharing across a model. Let's say you have a list that needs a to be limited to contain no more than 10 elements, and that list is used throughout the model any time you refer to, say, "widgets". With inline syntax, most people would inline the list in multiple places and repeat the constraint trait rather than share the common definition. The problem there is that if you ever need to change from 10 to something else, you have to update multiple places in the model.

So this is great:

```
structure User {
    names: UserNames
}

structure UserNameSummary {
    names: UserNames
}

@length(max: 10)
list UserNames {
    member: Name
}
```

Whereas this isn't great because it creates multiple places that need to be updated if constraints on UserNames ever changes:

```
structure User {
    @length(max: 10)
    names := [UserNames]
}

structure UserNameSummary {
    @length(max: 10)
    names := [UserNames]
}
```

As for naming, all shapes in Smithy have to have a name, so we'd have to synthesize one (inline I/O is just syntactic sugar that is exactly equivalent to writing it out long-form). It would have to be based on the container shape name + the member name to avoid conflicts with other similarly named structure members with divergent target shapes, documentation, etc (e.g., `Usernames`? or `UserNames`).

So for example:

```
structure User {
    names: [Name]
}
```

Changing to:

```
structure User {
    names: UserNames
}

list UserNames {
    member: Name
}
```

Would be considered identical models. Breaking the shape out would be something a team could do if they ever needed to add traits to the previously synthetic shape.

**Comment by kubukoz** [comment]
I have to admit I didn't consider naming conflicts when used in multiple shapes. Prefixing sounds good though, we don't see these shapes in our generated code anyway (list shapes are omitted in [smithy4s](https://github.com/disneystreaming/smithy4s/)-generated interfaces).

I think it's fair to assume these lists would mostly be used when there's just one of these lists: things like 

```
structure User {
    @length(max: 10)
    names := [Name]
}

structure UserNameSummary {
    @length(max: 10)
    names := [Name]
}
```

wouldn't be the norm - at that point it'd definitely be worth extracting into a proper list shape. The main usecase is really the simple lists with zero or few traits.

Maybe it's not so much of an improvement but it'd help a lot for people using Smithy syntax for domain modelling :)

**Comment by mtdowling** [comment]
If the synthetic list didn't support traits on the synthetic list or the member of the list, then we could use the target shape as the synthetic list's name (e.g., `NameList` or similar), cutting down on the number of duplicated synthetic lists. We could also automatically mark the synthetic list as `@private` to prevent any other consumer of your model from another namespace from referring to the synthetic list, and it makes it usable for defining traits (a typical practice for traits is to mark all shapes used by a trait `@private`).

To mitigate stuff like repeating the same constraint traits over and over on synthetic lists, we could probably add some kind of validation that looks at members that target lists and repeat the same trait.

**Comment by kubukoz** [comment]
Seems like quite a lot of work. Maybe it's better to just bite the bullet and type the extra characters 😅 

In the future it could be made easier with an editor code action (e.g. "create missing type" which would default to a list type based on some naming heuristics)

**Comment by mtdowling** [comment]
Yeah :). The Smithy core team is pretty divided on whether this would be a net positive too. Inline lists look great in docs and examples, but in practice we'd probably discourage their use at AWS since we want to add constraints to basically every list/set/map/string to make them bounded in some way, and we really don't want teams to fall into the trap of repeating themselves.

If we do add something for inline list definitions, it would be in 2.1 or later since we're working on wrapping up Smithy IDL 2.0.

**Comment by mtdowling** [comment]
Since we don't currently have plans for inline lists, I'll close this issue.
