### ISSUE TITLE
metadata validation is stricter

### ISSUE THREAD

**Issue by daddykotex** [awslabs/smithy#1352]
Previously, we've had code like that:

```kotlin
metadata thing = [
  {
    value: ActorId,
  },
  {
    value: examples.movies#ActorId,
  }
]

namespace examples.movies

string ActorId
string MovieId
```

And it was fine. Both the short version (no namespace), and the fully qualified name resolved correctly. When updating to 1.23.0 (at least in my language-server), I see the following:

![Screen Shot 2022-08-17 at 09 19 31](https://user-images.githubusercontent.com/5230460/185144386-6a92e9d9-e28c-480f-8ce4-c6060e3957ea.png)

The specific error I see is: `SyntacticShapeIdTarget: Syntactic shape ID `ActorId` does not resolve to a valid shape ID: `smithy.api#ActorId`. Did you mean to quote this string? Are you missing a model file?`

Although this makes sense to me, I'm surprised that this shows up. Is this expected?

I think it's coming from: https://github.com/awslabs/smithy/commit/a93711da822bc0f0b5730ea340efdf473b9d0023

In all cases, I'm not asking for a fix (using the fully qualified name works), maybe just some explanation. This can serve as documentation for people who see this error.

**Comment by mtdowling** [comment]
The metadata section is defined outside of any namespace, so the parser has to assume `smithy.api`, the prelude namespace, if a syntactic shape ID is used. The previous behavior was incorrect if this resolved to `examples.movies#ActorId` previously. There's an example of the expected behavior in the `Object Keys` section here from the v1 spec: https://awslabs.github.io/smithy/1.0/spec/core/idl.html#syntactic-shape-ids (and also present in the v2 spec).

We'll take an action item to update the spec to make this even more clear though.

**Comment by daddykotex** [comment]
That was the result of our internal discussion, so I'm not surprised. Thanks for confirming.

Feel free to close when the spec has been updated or right away if you want.
