### ISSUE TITLE
Default trait applied to streaming in version 1

### ISSUE THREAD

**Issue by 82marbag** [awslabs/smithy#1456]
The [data](https://github.com/awslabs/smithy-rs/blob/e74ecf348b67134a8f0a9abde5cf5b6f964a1327/codegen-server-test/python/model/pokemon.smithy#L39) member in this v1 model is being applied the `@default` trait. 

In the v1 spec there is no mention of this behavior.

**Comment by 82marbag** [comment]
Related: https://github.com/awslabs/smithy/issues/1380

**Comment by mtdowling** [comment]
You're seeing that in the in memory semantic model when using the Smithy libraries. The Smithy reference implementation automatically transforms all models to be valid for v2 semantics. It does that for anything that previously had a default zero value too. Tools that don't use or know about the default trait can simply ignore it. A code generator that supports both v1 and v2 should not ignore it. In Smithy v1, these members were implicitly considered to have a default by most server generators because it's not really possible to know if a streaming member was supplied but empty, so we decided to make that explicit in v2.
