### ISSUE TITLE
Quoted text grammar + parsing behavior

### ISSUE THREAD

**Issue by iancaffey** [awslabs/smithy#1491]
[Quoted text](https://awslabs.github.io/smithy/2.0/spec/idl.html#grammar-token-smithy-QuotedText) grammar has some restrictions about the quoted chars but the [IdlTextParser](https://github.com/awslabs/smithy/blob/main/smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlTextParser.java) lets them all through. 

Not really the biggest deal as the only commonly used character that's outside the grammar that can be parsed is a horizontal tab.

Is it worth/necessary updating the grammar to explicitly support this?

Bringing it up here to make sure I get it right in the [grammar of the IntelliJ Plugin](https://github.com/iancaffey/smithy-intellij-plugin/blob/main/src/main/grammar/Smithy.bnf).

**Comment by mtdowling** [comment]
Ah you're right. Given we've never validated that a literal tab isn't used in a Smithy IDL model, the safest thing to do is allow literal tab in the grammar. This deviates from what JSON supports, but I suspect tabs have been used in model strings. We should also add validation to disallow null, backspace, etc, since those shouldn't be supported and almost certainly have never been used in a model.

**Comment by milesziemer** [comment]
Fixed by https://github.com/awslabs/smithy/pull/1535
