### ISSUE TITLE
Default and constraint traits

### ISSUE THREAD

**Issue by 82marbag** [awslabs/smithy#1500]
What is the expected behavior when default and constraint traits are both applied? What happens if the two don't agree (the default value is outside the constraints)?

**Comment by david-perez** [comment]
A related discussion was in https://github.com/awslabs/smithy/issues/1121.

**Comment by mtdowling** [comment]
They have to agree with the exception of the range trait. I think we need to add some of this content to the spec, but you can see the rules here: https://github.com/awslabs/smithy/blob/main/designs/defaults-and-model-evolution.md#default-value-constraints

From that link:

The @default trait accepts a document type. The value of the trait MUST be compatible with the shape targeted by the member and adhere to the following constraints:
* The default value of an enum or intEnum MUST match one of the enum values.
* The default value of a string MUST be compatible with any length, enum, or pattern traits.
* The default value on a list or map MUST be compatible with a length trait, if present.
* The default value on a numeric type SHOULD be compatible with a range trait, if present. It was a common pattern in Smithy IDL 1.0 to define a numeric type with a default zero value, but require that the value be greater than zero. This specific validation is relaxed in order to not modify these types or need to drop the range constraint.

**Comment by 82marbag** [comment]
Are all these checks implemented in smithy already? Can we trust a model has already performed static checks?

I've seen at least `@range` constraints are validated

**Comment by mtdowling** [comment]
Yep!
