### ISSUE TITLE
NeighborProvider ignores Unit in operations

### ISSUE THREAD

**Issue by kubukoz** [awslabs/smithy#1540]
Given this code (runnable with `scala-cli https://gist.github.com/kubukoz/2a6129c307d0a16866448b7b4cccccc4`, using https://scala-cli.virtuslab.org/):

```scala
//> using lib "software.amazon.smithy:smithy-model:1.26.4"
//> using scala "2.13.10"
import software.amazon.smithy.model.Model
import software.amazon.smithy.model.neighbor.NeighborProvider
import software.amazon.smithy.model.shapes.ShapeId

import scala.jdk.CollectionConverters._

object demo extends App {

  val model = Model
    .assembler()
    .addUnparsedModel(
      "test.smithy",
      """$version: "2"
        |namespace test
        |
        |operation Hello { output: Unit, input: Unit
        |}
        |""".stripMargin,
    )
    .assemble()
    .unwrap()

  println(
    NeighborProvider
      .of(model)
      .getNeighbors(model.expectShape(ShapeId.from("test#Hello")))
      .asScala
      .toList
  )

}
```

the output is an empty list. However, if you change `operation` to `union`, both member shapes show up, and if you walk the shapes with a `Walker` you'll see that the members have a neighbor connection to `Unit`.

I believe this is slightly confusing and potentially invalid. I realize that `Unit` is a special shape in some ways, but it seems to get special handling (specifically when it's an operation input/output!) in a way that may not be expected - for example, if you try to build a closure of shapes using something like [smithy-translate's transitive module](https://github.com/disneystreaming/smithy-translate/blob/ec7d567f86ed60b3336f467275a5578e9e00f245/modules/transitive/src/closure/TransitiveModel.scala).

The behavior is the same if you skip the input/output completely and rely on the Unit default.

**Comment by mtdowling** [comment]
The rationale in added docs in the commit that made this change still makes sense to me - https://github.com/awslabs/smithy/commit/f00cdf79371b34050f267b7ba8c813bccef9f594. We considered Unit special for operation input/output and wouldn't have been able to backward compatibly add the concept with this treatment.

**Comment by kubukoz** [comment]
Interesting... so if an implicit `input: Unit` was added, it would've referred to the local `Unit`, not `smithy.api#Unit`?

**Comment by mtdowling** [comment]
Some languages would, yeah. How a language generates Unit is language-specific. Languages with a kind of unit type could use the language built-in version if that's idiomatic.

The issue was that many teams that use Smithy already defined a shape named Unit (for example, to describe units of measurement), and adding Unit as part of the [closure of a service](https://smithy.io/2.0/spec/service-types.html#service-closure) without a team opting in to it caused naming conflicts. If/when a team targets Unit from a tagged union member, then that would be opt-in, and they could handle any necessary renames when they add it.

If you wanted the Unit neighbor, could you decorate NeighorProvider with your own implementation that adds implicit Unit relationships between operations and input/output?

**Comment by kubukoz** [comment]
yeah, I think that would work. But for our usecase (computing a closure) we can just add Unit to the closure at all times.

Thanks for the explanations!
