### ISSUE TITLE
Support for generating Smithy models from JSON schema?

### ISSUE THREAD

**Issue by wtrocki** [awslabs/smithy#1588]
Hi

I'm investigating smithy as a project for general-purpose client generation.
Is there any way to generate Smithy models from OpenAPI schema?

As workaround right now I'm generating Java Pojos using OpenAPI generator and then discovering them using Smithy?
Would community accept such extension capability or this is something against Smithy architecture?

**Comment by cmoher** [comment]
we recommend [Smithy-translate](https://github.com/disneystreaming/smithy-translate), open-source tooling from Disney Streaming that enables converting Open API to Smithy. From their documentation: Because Smithy is a more constrained format than OpenAPI, this conversion is partial. This means that a best effort is made to translate all possible aspects of OpenAPI into Smithy and errors are outputted when something cannot be translated. When errors are encountered, the conversion still makes a best effort at converting everything else. This way, as much of the specification will be translated automatically and the user can decide how to translate the rest.

https://github.com/disneystreaming/smithy-translate

**Comment by wtrocki** [comment]
Awesome info! I would recommend adding that library to the main page as it is pretty much going to enable many to migrate to the smithy. It works quite well for my use cases.
