### ISSUE TITLE
Handling of null in default trait

### ISSUE THREAD

**Issue by lewisjkl** [awslabs/smithy#1601]
I have a question about what I think is an ambiguity in the current documentation. So first, take the example of:

```smithy
@default("test")
string MyString

structure MyStructure {
  str: MyString = null
}
```

The documentation, about an example like this, states that `The @default trait on a structure member can be set to null to explicitly indicate that the member has no default value or to override the default value requirement of a targeted shape.` This leads me to believe that in this example, `MyStructure$str` has no default value. By extension I would assume that any time the default trait has a "null" value provided, it means there is no default. (Document types might be the only exception to this?)

However, in the javadoc for the `DefaultTrait` says, `Indicates that a shape is defaulted, meaning a zero value is used when one is not provided.` This statement leads me to believe that a null default trait means the default is actually the `zero value`. So in:

```smithy
structure MyStructure {
  @default
  str: String
}
```

I would think that, based on the JavaDoc, this means that `MyStructure$str` has a default value of `""` (empty string).

---

Back to the comment I made about `Document` types above, I think the following example shows one ambiguous case:

```smithy
@default("test")
document MyDoc

structure MyStructure {
  doc: MyDoc = null
}
```

Here does this mean that `MyStructure$doc` has a default of `null`, or that it has no default at all?

Would love to have someone help me understand what I am missing here. Thanks so much!

**Comment by mtdowling** [comment]
Setting a member to have a default value of null is only useful if the shape targeted by the member defines a default value. It's only meaning is that it cancels out the default value of the target shape. Members with no default value defined are always assumed to have no default value in Smithy IDL 2 (that's exactly equivalent to setting the default value of the member to `null`; we could have called it `None` or some other keyword but chose null for familiarity). Setting a document type null is also meaningless and there's no way to set a document type to have a default value of null since that's already the assumed value if it isn't specified.

> However, in the javadoc for the DefaultTrait says, Indicates that a shape is defaulted, meaning a zero value is used when one is not provided. This statement leads me to believe that a null default trait means the default is actually the zero value

Ah, the DefaultTrait javadocs are wrong and reflect a previous iteration on how we were planning default values.
