### ISSUE TITLE
AWS JSON 1.0 and 1.1 Protocol test

### ISSUE THREAD

**Issue by yisraelU** [awslabs/smithy#1634]
how are the following tests meant to be used . There is no endpoint trait applied to the operation in question .
the tests are over here 
https://github.com/awslabs/smithy/blob/main/smithy-aws-protocol-tests/model/awsJson1_1/endpoint-paths.smithy 
and over here
 https://github.com/awslabs/smithy/blob/main/smithy-aws-protocol-tests/model/awsJson1_0/endpoint-paths.smithy

**Comment by JordonPhillips** [comment]
Those existing tests are meant to test behavior when the endpoint provided by the customer contains a path segment, though tests for the endpoint trait should also be added

**Comment by yisraelU** [comment]
@JordonPhillips I guess what I am asking is how does one run this test.
My current understanding , is that generally there is a Params structure that defines the input to the test and the goal is to see if the generated request from the Params is equal to the request defined in the HttpRequestTest.
So for this test I would have expected a Params that would have stipulated that the endpoint contain `/custom`

**Comment by JordonPhillips** [comment]
`host` is an input parameter, essentially representing a configured static uri. In the AWS CLI, for example, this would be what you provide to `--endpoint-url`, though without the scheme. Since it isn't part of the individual operation input shape, it's not part of `params`. There is also `resolvedHost`, which maps more cleanly to the hostname of the resolved uri and is only used in client testing to compare against the resolved uri.

**Comment by yisraelU** [comment]
@JordonPhillips TY for clarifying
