### ISSUE TITLE
Converting protocol awsJson1_0 to OpenAPI

### ISSUE THREAD

**Issue by hugobeaujour** [awslabs/smithy#1701]
Hello guys,

First of all i want to say that this standard is amazing, and even thought we can't switch to Smithy we find it very interesting.
Secondly we want to thanks you to develop a converter to OpenAPI, even if it's not perfect, it's really useful to us.

In our product, we're using a lot of OpenAPIs, and one of them is the OpenAPI of AWS obviously.
We succeeded to build an OpenAPI JSON file from the Smithy file that we found in the AWS SDK.
For the lambda Smithy file for example, it went flawlessly and we're already using it. But for some others like DynamoDB for example, it requires a different protocol than `application/json` and so the smithy-build process fail to build the final OpenAPI json file because of that.

The error that we got is the following :
`Unable to find an OpenAPI service provider for the 'aws.protocols#awsJson1_0' protocol when converting 'com.amazonaws.dynamodb#DynamoDB_20120810'. Protocol service providers were found for the following protocol classes: ['software.amazon.smithy.aws.traits.protocols.RestJson1Trait']`

As we understand it, this smithy-build doesn't know how to transform this protocol to OpenAPI, but does know how to transform RestJson1Trait.

Is there a build-in way to make it work ? And make him know how to transform this protocol
We are willing to patch this ourselves if there is a way. Just let us know what kind of code and where it needs to be

Thanks again

**Comment by mtdowling** [comment]
Thanks for the kind words.

The only protocol used by AWS that’s compatible with OpenAPI is restJson1. awsJson_* is a strictly RPC protocol that relies on things like headers for routing requests and reuses the same method and path for each operation, which isn’t supported by OpenAPI.

I wouldn’t recommend using OpenAPI generated clients instead or AWS clients as AWS clients provide many more features like endpoint resolution, signing support for sigv4 and sigv4a, token/bucket adaptive retries, service specific customizations, and they automatically support changing to more improved serialization formats when services update since Smithy is protocol agnostic. For example, if we add support for a binary encoding, clients can update without a breaking change.
