### ISSUE TITLE
CLI: how to pass credentials?

### ISSUE THREAD

**Issue by kubukoz** [awslabs/smithy#1768]
Hi! I wanted to give the CLI a try in my company project, but unfortunately it didn't work - the `smithy-build.json` file contains repository URLs that look roughly like: `https://user@hostname.com/maven`. To provide credentials, we rely on:

1. for our builds (using a custom system based on [Mill](https://com-lihaoyi.github.io/mill/mill/) - environment variables
2. for LSP - pre-fetching the dependencies so that they're in the [Coursier](https://get-coursier.io/) cache at `~/Library/Caches/Coursier/v1/https/user%40hostname.com/maven`.

I can see that the CLI does not use Coursier, but a specialized Maven resolved based on Aether. Is there a way for it to get credentials from environment variables, or some other way that doesn't require storing them in the build file?

Additionally, I would like to talk about credentials for the LSP, so that we don't have to rely on pre-populating the cache - but that discussion can be had another day, as the workaround we have works reasonably fine.

**Comment by kubukoz** [comment]
nice! Is that supported in the LSP?

**Comment by srchase** [comment]
> nice! Is that supported in the LSP?

Currently it does not. The LSP uses its own separate dependency resolver. We'd like to move the LSP to use the same dependency resolution so that this would be supported.

For now, I think adding support for `SMITHY_MAVEN_REPOS` environmental variable would be the best option for setting credentials that could be used between the CLI and LSP.

I added this issue on the LSP: https://github.com/awslabs/smithy-language-server/issues/107

**Comment by kubukoz** [comment]
Got it. May I know why you chose not to stick to Coursier? Was it the (admittedly, heavy) Scala dependency or something else?

**Comment by srchase** [comment]
Closing this as it is supported in Smithy, and there's a separate issue tracking adding the same capabilities to the Language Server.
