### ISSUE TITLE
[Feature Request] Autogen requestTemplates for Api Gateway Integration trait by using http traits

### ISSUE THREAD

**Issue by khaing211** [awslabs/smithy#272]
Motivation: we want to use `aws` as ApiGateway integration instead of `aws_proxy`.  The difference between `aws` and `aws_proxy` is [well-documented](https://stackoverflow.com/questions/41648467/getting-json-body-in-aws-lambda-via-api-gateway). However, the good thing of `aws` integration is the handler code does not have to do deserialization/serialization. We want to use this [de]serialization for GET request. We already have a dumb library that is able to generate Java POJO from generated Swagger spec. These POJO is already used in POST request to [de]serialize the json. We want to use these POJOs the same way for GET as it is for POST. However, we DO NOT want to manually specify `requestTemplates` on [aws.apigateway#integration](https://awslabs.github.io/smithy/spec/amazon-apigateway.html#aws-apigateway-integration-trait). 

Upon a cursory reading of [AddIntegrations](https://github.com/awslabs/smithy/blob/master/smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddIntegrations.java), `AddIntegrations` is able to use `cors` trait from `http` traits. We think we could auto-generate `requestTemplates` from the information providing by [httpLabel](https://awslabs.github.io/smithy/spec/http.html#httplabel-trait), [httpPayload](https://awslabs.github.io/smithy/spec/http.html#httppayload-trait), `httpQuery`, and `httpPrefixheaders` traits.

We wonder

* Is this something that AWS[Labs] have considered and discarded or planned to do?
* Is this architectural sound? 
  * We don't want to shove this logic into `AddIntegrations` (if we could), because there could be client who does not want it. Furthermore, this logic can't support complicated/nested operation's input structure definition.
  * Smithy claims to be "extensible", but we have not found any straightforward guide to implement a custom own trait.
* What are the steps to get pull request accepted?
  * (provided that one welcome pull request) any suggestion on feature flag on traits to enable/disable this feature?

**Comment by mtdowling** [comment]
If I understand correctly, the request here is to add the ability to generate request templates that make some set of GET and POST requests rewritten to the same kind of request?

> Smithy claims to be "extensible", but we have not found any straightforward guide to implement a custom own trait.

Sorry about that. We plan on tackling more documentation like this soon. For now, you could look at how existing traits are implemented. For example, this directory contains many different types of traits, and also validators that can be used to ensure traits are applied correctly: https://github.com/awslabs/smithy/tree/master/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/apigateway. Traits and validators need to be registered in META-INF/services so that they're detected as service providers (for example, https://github.com/awslabs/smithy/tree/master/smithy-aws-traits/src/main/resources/META-INF/services). Then you just need to add your package to the classpath, and it's automatically applied when loading traits for a shape.

> What are the steps to get pull request accepted?

If it's a smaller change, then just opening a pull request with a good description and test cases is all it takes. If it's a larger change, it's usually to discuss them first before putting in a lot of work (like this issue 👍).

**Comment by khaing211** [comment]
> If I understand correctly, the request here is to add the ability to generate request templates that make some set of GET and POST requests rewritten to the same kind of request?

Correct.  GET requires `requestTemplates` transformation, because the GET Http does not have a body like POST.

About 2nd and 3rd comments, does this mean that your opinion leaning toward an implementation that use a separate trait as a marker to activate the feature.

**Comment by mtdowling** [comment]
At this point, I think we'd need more evidence that this is a common use case in order to add it to Smithy itself.

When I think about serialization formats like this, I typically lean towards relying on protocol abstractions (for example, to smooth over the isomorphism between GET and POST requests). We're working on ways to make it easier to implement a custom protocol in both the model and in codegen, but it's still a WIP. In the meantime, I do think a customization would be the right approach here, though it will definitely take some work.

**Comment by mtdowling** [comment]
This is not something we'll provide as a built-in feature to Smithy's OpenAPI converter at this time, but it's something that could be done using an extension registered as a service provider. Take a look at https://github.com/awslabs/smithy/blob/master/smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/Smithy2OpenApiExtension.java for a starting point. You could implement a mapper that maps over different parts of the OpenAPI model being built: https://github.com/awslabs/smithy/blob/95e0dc6061f32bea64ceb7eff3f262e69a35528b/smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiMapper.java#L45. An `OpenApiMapper` is a lot like an event based system, but it uses specific interface methods and return values. Hope this helps.
