### ISSUE TITLE
Better explain the build process

### ISSUE THREAD

**Issue by jrhill85** [awslabs/smithy#437]
So the readme of the package says

> The Smithy Gradle Plugin is the best way to get started with building a Smithy model.

which leads me to believe it's not the only way implemented here?

There's a page on awslabs.github.io/smithy called "SmithyBuild" which seem to reference something other than a Gradle plugin (it's a different page but I can't tell 100% if this is just configurations and prerequisites or is really an alternative to the gradle plugin??) it doesn't reference Gradle at all on the page, just "building" in an abstract way.

There are also pages about converting to openapi - is this something different from "SmithyBuild"? (Note, here it references "smithy-build" which sounds more like a command line tool?) but there's again nothing about Gradle or links to the Gradle stuff which makes it seem like there's some other tool out there somewhere?

Can you tighten up the expectation around what is actually supported for building Smithy? Does it require Gradle? Does it specifically require Kotlin or a JVM language? Is there a CLI or some standalone build tool that's just missing documentation?

Also, can you link to the "issues" area of this github repo from the github.io pages? (Maybe as a "contact us" kind of link? There's no clear way to give feedback from those pages, and requires either an understanding of github pages or some googling)

**Comment by jrhill85** [comment]
To clarify a little: I do see there are some folders called `smithy-build` and `smithy-cli` but what are they...? Standalone products? Results of some kind of Gradle build, if I had some kind of Gradle project or something? Just experimental libraries not hooked up to anything yet?

**Comment by srchase** [comment]
The Gradle plugin is how you build Smithy models.  The plugin [depends](https://github.com/awslabs/smithy-gradle-plugin/blob/master/build.gradle.kts#L30-L31) on both the CLI and SmithyBuild.

SmithyBuild is where most of the brains are for building Smithy models. It handles the complexity of transforming models, applying projections and plugins (such as the OpenAPI plugin  for converting Smithy models). A smithy-build.json file provides the configuration for SmithyBuild. 

The Gradle plugin is just a light wrapper around SmithyBuild. We made it this way so that it's easy to plugin Smithy's model transformation logic into different build systems (for example, inside of Amazon, we hooked Smithy up to our internal build system). Gradle is still really useful though because we use it for dependency management and for building JARs.

For now we are only using the CLI as an implementation detail and haven't prioritized shipping it as a standalone tool.

You should use the Gradle plugin if you want to generate OpenAPI models from your Smithy model, and the way you hook this up is by adding the "openapi" plugin to your smithy-build.json file. The documentation [here](https://awslabs.github.io/smithy/1.0/guides/converting-to-openapi.html#converting-to-openapi-with-smithy-build) shows how the classpath dependency for the plugin can be added to the Gradle plugin the with examples of how the "openapi" plugin is configured via the smithy-build.json file.

We can definitely tighten the documentation to make the relationship between SmithyBuild and the Gradle plugin more clear and provide some context on how the CLI is involved (if not provide actual documentation for it).

Appreciate this and any other feedback you'd care to share as you dig into using Smithy.
