### ISSUE TITLE
Should operation errors be a union instead of an array ? 

### ISSUE THREAD

**Issue by Baccata** [awslabs/smithy#600]
The fact that operation errors is an array when smithy supports the concept of union creates a somewhat weird dissonance : the two are just modelling "oneOf" concepts, and therefore are not really orthogonal to each other. 

Should they be reconciled ?

**Comment by mtdowling** [comment]
I don't think so; `errors` define a list of possible errors for an operation, and the targeted error shape names inherently provide the discriminating "tag". `union` in Smithy is actually *tagged union*, and they require an explicit tag for each variant. Moving errors to a union in Smithy would mean that modelers would have to provide explicit tags for errors, which wouldn't be great since error "tags" 1:1 correspond to the name of the error shape (leaving models either up for the potential of errors, or needing validation to ensure a 1:1 correspondence). We also currently have no plans on adding an untagged union.

**Comment by Baccata** [comment]
That is fair enough, thanks for the reply :+1:
