### ISSUE TITLE
Is there a plan for APIGateway to export Smithy at some point?

### ISSUE THREAD

**Issue by adam-fowler** [awslabs/smithy#703]

**Comment by mtdowling** [comment]
It's something we've thought about. What's the use case / workflow you had in mind?

**Comment by adam-fowler** [comment]
I'm the main developer on Soto, the third party Swift SDK for AWS. I have been looking into generating the Swift versions of the AWS service files from the Smithy file descriptions. While doing this I did a little investigation on whether I could generate Swift code for my own custom Smithy and it worked out pretty good.

The use case would be generating client interfaces from API gateway setups. I guess I could do this from the OpenAPI or Swagger but I already have a code generation tool that takes Smithy as input.

**Comment by mtdowling** [comment]
Sorry for the delay and thanks for the context! I'll pass this feature request on to the API Gateway team.

In my personal experience, and what I observe other teams doing with Smithy at Amazon, is that typically the package that generates OpenAPI models from Smithy to export to API Gateway also handles generating the clients from Smithy. This way, there's no need to call a web service and need network access to generate clients, nor is there any kind of potential for lost metadata due to converting Smithy -> OpenAPI -> API Gateway -> Smithy.

**Comment by adam-fowler** [comment]
Seems strange that AWS would treat their own file format as a second case citizen needing to be converted to OpenAPI before being used with API Gateway. I guess all these things take time.

I guess the question can be asked in the other way. Will API Gateway import Smithy? Given the work pattern you mention above that would make more sense.

**Comment by mtdowling** [comment]
I'm closing this issue since this is not currently planned. But we hear you, and we let the API Gateway know about this feature request for both importing and exporting Smithy models.
