### ISSUE TITLE
Restricting api input RequestBody in generated OpenAPI 3.0 json

### ISSUE THREAD

**Issue by chiujack** [awslabs/smithy#710]
Hi all! 

I am currently using Smithy to generate an OpenAPI 3.0.2 json for API Gateway. I would like to be able to reject/restrict api requests when the request body contains unexpected properties.

For an API that has the below input request,
```
apiInputRequestContent: {
    validProp1: string,
    validProp2: string
}
```
I would like to have the following request be rejected due to the request body containing extra properties.
```
invalidRequestBody: {
    validProp1: 'value1',
    validProp2: 'value2',
    invalidProp1: 'value3'
}
```

From my understanding, OpenAPI 3.0 supports this functionality by setting `additionalProperties = false` in the input schema but I was unable to find a similar setting in Smithy. Based on the settings for [mapStrategy](https://awslabs.github.io/smithy/1.0/guides/converting-to-openapi.html?highlight=additionalproperties), there doesn't seem to be a way to turn off that setting in Smithy. 

I am looking to see if there is an existing feature of Smithy to set this or if you have any recommendation to

**Comment by kstich** [comment]
Smithy doesn't provide this functionality out of the box. Having `additionalProperties: false` set on an object means you can't do things like remove an optional parameter without breaking customers who send them. This, and other potential for the request body to become out of sync with the service definition, can cause issues for customers of your API.

If you still require this property to be set, you can register an implementation of [the `Smithy2OpenApiExtension` interface](https://awslabs.github.io/smithy/javadoc/1.6.1/software/amazon/smithy/openapi/fromsmithy/Smithy2OpenApiExtension.html) that uses `getJsonSchemaMappers()` to supply a custom [`OpenApiJsonSchemaMapper`](https://awslabs.github.io/smithy/javadoc/1.6.1/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapper.html) to set this property on the underlying JSON Schema for the structures.

**Comment by mtdowling** [comment]
Hopefully kstich was able to answer your question. I think in general, because APIs evolve over time, being overly restrictive about additional fields and rejecting requests should not be the default for Smithy (for a related example, this is something that I've seen cause a ton of issues in Jackson deserialization of Java POJOs). Of course there are tradeoffs to this-- for example, a client could have typo'd a parameter name, but since we expect most clients are generated from the model, this is hopefully an exception. All that said, there are ways you can achieve this in Smithy if you really need to, as kstich laid out. I'll go ahead and close this, but let us know if you further questions.
