### ISSUE TITLE
Nested sets should return false for isBoxed()

### ISSUE THREAD

**Issue by wooj2** [awslabs/smithy#752]
Given this smithy model:
```
@idempotent
@http(uri: "/XmlEnumNestedSet", method: "PUT")
operation XmlEnumNestedSet {
    input: XmlEnumNestedSetInputOutput,
    output: XmlEnumNestedSetInputOutput
}


structure XmlEnumNestedSetInputOutput {
    fooEnumSet: NestedFooEnumSet
}

set NestedFooEnumSet {
    member: FooEnumSet,
}
```

It seems that an SDK should generate the following type:
```
public struct XmlEnumNestedSetInput: Equatable {
    public let fooEnumSet: Set<Set<FooEnum>>?
   //..snip.../
}
```
This definition in the `struct` above correct for `fooEnumSet` because it is of the type `Set<Set<FooEnum>>?`.  Specifically, the inner set is not optional, because Sets are required to be dense.  (if this is not correct, please let me know)

Going a step further, when attempting to generate a serializer for this Shape, we are seeing the following:
```
member = (passed into from some function) : XmlEnumNestedSetInput$fooEnumSet
memberTarget = member.target : aws.protocoltests.restxml#NestedFooEnumSet
nestedMemberTarget = memberTarget.member.target : FooEnumSet
```

**Observation:**
We are observing that when calling `isBoxed()` on `nestedMemberTarget` is returning `true`

**Expected Behavior:**
We are expecting that calling `isBoxed` on `nestedMemberTarget` should return false, since sets must not be null.

**Comment by kstich** [comment]
I believe this is the expected behavior. The `NestedFooEnumSet` shape itself, what you're calling `isBoxed` on, is independent of a container and therefore is [inherently boxed/nullable](https://awslabs.github.io/smithy/1.0/spec/core/model.html#default-structure-member-values). Members of [sets are _not nullable_](https://awslabs.github.io/smithy/1.0/spec/core/model.html#set), so you shouldn't need to worry about checking the nullability of the member's target when generating code.
