### ISSUE TITLE
Allow smithy.api#jsonName trait to target union members 

### ISSUE THREAD

**Issue by Baccata** [awslabs/smithy#953]
It is currently [restricted to structure members](https://github.com/awslabs/smithy/blob/main/smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy#L293-L295). 

I think it should be possible for it to target union members as well.

**Comment by Grundlefleck** [comment]
> The jsonName trait, as it is, is kind of a concession to the reality of needing to support existing services.

We are running into similar problems trying to match existing HTTP API style guides where we have standardised on `snake_case` property names in JSON objects. We do not yet provide SDKs universally, so we still have to take care with JSON shapes in the wire format, as we expect developers to use JSON directly.

We were getting by with `@jsonName` annotations, but hit this roadblock on our first use of Smithy union types. 

I would have expected to be able to do the following (example from the Smithy [docs](https://awslabs.github.io/smithy/1.0/spec/core/model.html#union)):
```
union PlayerAction {
    quit: Unit,

    @jsonName("move_about")
    moveAbout: DirectedAction,

    @jsonName("jump_around")
    jumpAround: DirectedAction
}
```
so that awsRestJson1 protocol would adapt the input and output shapes. For reference we're using smithy-typescript to generate the validation code, and it's all working well.

I'm worried that this approach we're taking is repeatedly going to bump into issues attempting to curate JSON shapes via the Smithy models alone. @JordonPhillips do you think we should be approaching this differently, so that we are more aligned with Smithy and can leverage as much as possible out of the box? Or is enforcing style guides on a serialization format fundamentally misaligned with Smithy?

**Comment by Grundlefleck** [comment]
@mtdowling just a note on implementation as I didn't see it mentioned. While the `@jsonName` trait can differ from the union member names, as a user I'd expect the same constraints of having unique `@jsonNames` within a union, and failing validation if I have duplicates.

**Comment by mtdowling** [comment]
`jsonName` is now supported on members. This will go out in the next release.

**Comment by Baccata** [comment]
🎉 ❤️
